# Generated by Django 3.2 on 2022-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('msg', models.TextField(verbose_name='additionalMessage')),
                ('text', models.TextField(verbose_name='text')),
                ('target', models.TextField(verbose_name='target')),
                ('stance', models.TextField(verbose_name='stance')),
            ],
        ),
    ]
